### ISSUE TITLE
kong_setup.rb is not present (which is mentioned in manual setup guide)

### ISSUE THREAD

**Issue by utmishra** [octoai/apihandler#8]
For the instruction "Creating users of Octo-platform" under Manual setup guide , `kong_setup.rb` file is required. However I am not able to find any such file. There is a ruby script called create_kong_config.rb, which didn't run. Looking into it I found that `require 'curb'` was returning error. I added `gem curb` and the script started running but failed with following error:

`./create_kong_config.rb:180:in`create': undefined method `[]' for nil:NilClass (NoMethodError)
    from ./create_kong_config.rb:238:in <main>
`

Thanks!

**Comment by pranny** [comment]
The correct file is named `create_kong_config.rb` and the right way it to also pass the config directory. Something like below

``` bash
$ bin/create_kong_config.rb ~/workspace/octo/current/config/
Loading from Config file: /Users/pranav/workspace/octo/current/config//config.yml
Loading from Config file: /Users/pranav/workspace/octo/current/config//kong_config.yml
I, [2016-08-09T17:24:30.009903 #64072]  INFO -- Octo: Octo booting up.
I, [2016-08-09T17:24:30.029038 #64072]  INFO -- Octo: I'm connected now.
I, [2016-08-09T17:24:30.039348 #64072]  INFO -- Octo: Setting callbacks.
I, [2016-08-09T17:24:30.045275 #64072]  INFO -- Octo: {"data"=>[{"upstream_url"=>"http://192.168.99.100:9001/update_push_token", "strip_request_path"=>true, "request_path"=>"/update_push_token", "id"=>"91ad4f1e-2834-4bdd-a42a-de61e1e872c6", "created_at"=>1468495646000, "preserve_host"=>false, "name"=>"UpdatePushToken"}, {"upstream_url"=>"http://192.168.99.100:9001/events", "strip_request_path"=>true, "request_path"=>"/events", "id"=>"c13febf5-757b-46e0-8430-c56256c766a7", "created_at"=>1468495646000, "preserve_host"=>false, "name"=>"events"}], "total"=>2}
I, [2016-08-09T17:24:30.056998 #64072]  INFO -- Octo: Attempting to create new enterprise with name: Jaobng
I, [2016-08-09T17:24:30.391932 #64072]  INFO -- Octo: Created templates for Enterprise: Jaobng
I, [2016-08-09T17:24:30.394817 #64072]  INFO -- Octo: Created segents for Enterprise: Jaobng
I, [2016-08-09T17:24:30.484397 #64072]  INFO -- Octo: Attempting to create new enterprise with name: Octo
I, [2016-08-09T17:24:30.491406 #64072]  INFO -- Octo: Created templates for Enterprise: Octo
I, [2016-08-09T17:24:30.496170 #64072]  INFO -- Octo: Created segents for Enterprise: Octo
I, [2016-08-09T17:24:30.577414 #64072]  INFO -- Octo: Adding Plugin key-auth for api events
I, [2016-08-09T17:24:30.583918 #64072]  INFO -- Octo: Adding Plugin key-auth for api UpdatePushToken
I, [2016-08-09T17:24:30.589688 #64072]  INFO -- Octo: Adding Plugin cors for api events
I, [2016-08-09T17:24:30.596629 #64072]  INFO -- Octo: Adding Plugin cors for api UpdatePushToken
I, [2016-08-09T17:24:30.602885 #64072]  INFO -- Octo: Adding Plugin rate-limiting for api events for consumer: 643c19e5-a913-49d7-bc4d-ed9c9c8183d8
```

Apologies for the outdated setup guide. It will be updated soon. Also, will add the `curb` to Gemfile so it does not throw error anymore.

**Comment by utmishra** [comment]
On running create_kong_config.rb, the output is as follows:

`Loading from Config file: /Users/utkarsh.mishra/dev/tools/octo/config//config/config.yml`
`Loading from Config file: /Users/utkarsh.mishra/dev/tools/octo/config//config/kong_config.yml`
`Loading from Config file: /Users/utkarsh.mishra/dev/tools/octo/config//config.yml`
`Loading from Config file: /Users/utkarsh.mishra/dev/tools/octo/config//kong_config.yml`
`I, [2016-08-09T17:44:21.891165 #13758]  INFO -- Octo: Octo booting up.`
`I, [2016-08-09T17:44:21.895575 #13758]  INFO -- Octo: I'm connected now.`
`I, [2016-08-09T17:44:21.902239 #13758]  INFO -- Octo: Setting callbacks.`
`/Users/utkarsh.mishra/.rvm/gems/ruby-2.1.5/gems/curb-0.9.3/lib/curl/easy.rb:68: warning: uncaught exception from callback`
`/Users/utkarsh.mishra/.rvm/gems/ruby-2.1.5/gems/curb-0.9.3/lib/curl/easy.rb:68: warning: uncaught exception from callback`
`/Users/utkarsh.mishra/.rvm/gems/ruby-2.1.5/gems/curb-0.9.3/lib/curl/easy.rb:68: warning: uncaught exception from callback`
`I, [2016-08-09T17:44:21.904583 #13758]  INFO -- Octo: Attempting to create new enterprise with name: Jaobng`
`W, [2016-08-09T17:44:22.006160 #13758]  WARN -- Octo: Not creating client as client name exists`
`I, [2016-08-09T17:44:22.006205 #13758]  INFO -- Octo: Attempting to create new enterprise with name: Octo`
`W, [2016-08-09T17:44:22.007726 #13758]  WARN -- Octo: Not creating client as client name exists`
`/Users/utkarsh.mishra/.rvm/gems/ruby-2.1.5/gems/curb-0.9.3/lib/curl/easy.rb:68: warning: uncaught exception from callback`
`./create_kong_config.rb:193:in`create': undefined method `[]' for nil:NilClass (NoMethodError)
    from ./create_kong_config.rb:238:in <main>'`

Is this happening because all configurations are already set ?

**Comment by pranny** [comment]
It should not have been that case. Is your `kong-config.yml` all good?

**Comment by pranny** [comment]
If your kong up and running properly? You can use [kong dashboard](https://github.com/PGBI/kong-dashboard) to verify it is up and connected.

**Comment by utmishra** [comment]
I checked the kong status. Its running. Most of the output of create_kong_config.rb seems to be fine. There is only one error.

```
administrators-MacBook-Pro-52:bin utkarsh.mishra$ ./create_kong_config.rb ~/dev/tools/octo/config/
Loading from Config file: /Users/utkarsh.mishra/dev/tools/octo/config//config/config.yml
Loading from Config file: /Users/utkarsh.mishra/dev/tools/octo/config//config/kong_config.yml
Loading from Config file: /Users/utkarsh.mishra/dev/tools/octo/config//config.yml
Loading from Config file: /Users/utkarsh.mishra/dev/tools/octo/config//kong_config.yml
I, [2016-08-09T18:48:19.034191 #29750]  INFO -- Octo: Octo booting up.
I, [2016-08-09T18:48:19.039352 #29750]  INFO -- Octo: I'm connected now.
I, [2016-08-09T18:48:19.045668 #29750]  INFO -- Octo: Setting callbacks.
I, [2016-08-09T18:48:19.053038 #29750]  INFO -- Octo: {"data"=>[{"upstream_url"=>"http://127.0.0.1:9001/update_push_token", "strip_request_path"=>true, "request_path"=>"/update_push_token", "id"=>"a2460f8f-caf9-4e69-91ae-cbcdfe60ed28", "created_at"=>1470747335000, "preserve_host"=>false, "name"=>"UpdatePushToken"}, {"upstream_url"=>"http://127.0.0.1:9001/events", "strip_request_path"=>true, "request_path"=>"/events", "id"=>"4f54dffa-b046-49c2-8dac-cc945593ebf8", "created_at"=>1470747335000, "preserve_host"=>false, "name"=>"events"}], "total"=>2}
I, [2016-08-09T18:48:19.065337 #29750]  INFO -- Octo: Attempting to create new enterprise with name: Jaobng
W, [2016-08-09T18:48:19.191232 #29750]  WARN -- Octo: Not creating client as client name exists
I, [2016-08-09T18:48:19.191284 #29750]  INFO -- Octo: Attempting to create new enterprise with name: Octo
W, [2016-08-09T18:48:19.192616 #29750]  WARN -- Octo: Not creating client as client name exists
I, [2016-08-09T18:48:19.197198 #29750]  INFO -- Octo: Adding Plugin key-auth for api events
I, [2016-08-09T18:48:19.201917 #29750]  INFO -- Octo: Adding Plugin key-auth for api UpdatePushToken
I, [2016-08-09T18:48:19.205651 #29750]  INFO -- Octo: Adding Plugin cors for api events
I, [2016-08-09T18:48:19.209463 #29750]  INFO -- Octo: Adding Plugin cors for api UpdatePushToken
./create_kong_config.rb:208:in `block (3 levels) in create': undefined method `[]' for nil:NilClass (NoMethodError)
    from ./create_kong_config.rb:204:in `each'
    from ./create_kong_config.rb:204:in `block (2 levels) in create'
    from ./create_kong_config.rb:200:in `each'
    from ./create_kong_config.rb:200:in `block in create'
    from ./create_kong_config.rb:196:in `each'
    from ./create_kong_config.rb:196:in `create'
    from ./create_kong_config.rb:238:in `<main>'
```

My kong_config.yml is as follows:

`````` :clients:
  - :name: Jaobng
    :email: admin@jaobng.com
    :password: yothisisnotapassword
    :admin: false
    :rate-limiting:
      :day: 100000
      :minute: 100
      :second: 100
      :hour: 10000
      :month: 100000
      :year: 1000000000
  - :name: Octo
    :email: api@octo.ai
    :password: randompasswordhere
    :admin: true
:apis:
  - :name:  events
    :request_path: /events
    :upstream_url: http://127.0.0.1:9001/events
  - :name:  UpdatePushToken
    :request_path: /update_push_token
    :upstream_url: http://127.0.0.1:9001/update_push_token
:plugins:
  :key-auth:
    :apis:
      - :events
      - :UpdatePushToken
    :clients: all
    :config:
      :key_names: apikey
  :cors:
    :apis:
      - :events
      - :UpdatePushToken
    :clients: all
    :config:
      :methods: 'GET,POST'
      :origin: '*'
  :rate-limiting:
    :apis:
      - :events
    :clients:
      - Jaobng
:kong: 127.0.0.1:8001```
``````

**Comment by pranny** [comment]
https://github.com/octoai/apihandler/pull/9
